[package]
authors = ["Fuzen <fuzen@protonmail.com>"]
name = "melody"
version = "0.1.0"

[[bin]]
name = "melody"
path = "bin/melody/main.rs"
required-features = []

[dependencies]
app_dirs = "1.1.1"
config = "0.7.0"
cute = "0.3.0"
mp3-metadata = "0.3.0"
num-integer = "0.1"
rodio = "0.5.2"
tabwriter = "1.0.3"
