[package]
authors = ["Fuzen <fuzen@protonmail.com>"]
name = "melody"
version = "0.1.3"
license = "MIT/Apache-2.0"
description = "terminal Audio playback client"

[[bin]]
name = "melody"
path = "bin/melody/main.rs"
required-features = []

[dependencies]
cute = "0.3.0"
mp3-metadata = "0.3.0"
num-integer = "0.1.39"
rayon = "1.0.2"
tabwriter = "1.1.0"
rodio = "0.8.1"
directories = "1.0.2"
indicatif = "0.9.0"
rand = "0.5.5"
human-panic = "1.0.1"
