[package]
authors = ["Fuzen <fuzen@protonmail.com>"]
name = "melody"
version = "0.1.0"

[[bin]]
name = "melody"
path = "bin/melody/main.rs"
required-features = []

[dependencies]
cute = "0.3.0"
rodio = "0.5.2"
rtag = "0.3.5"
tabwriter = "1.0.3"
config = "0.7.0"
app_dirs = "1.1.1"
# termion = "1.5.1"
