[package]
authors = ["Fuzen <fuzen@protonmail.com>"]
name = "melody"
version = "0.1.4"
license = "MIT/Apache-2.0"
description = "terminal Audio playback client"
repository = "https://gitlab.com/Fuzen-py/Melody"
homepage = "https://gitlab.com/Fuzen-py/Melody"

[[bin]]
name = "melody"
path = "bin/melody/main.rs"
required-features = []

[dependencies]
mp3-metadata = "0.3.0"
num-integer = "0.1.39"
tabwriter = "1.1.0"
rodio = "0.13.0"
directories = "3.0.1"
indicatif = "0.15.0"
rand = "0.8.3"
human-panic = "1.0.1"
walkdir = "2.2.5"
